name: Lint
on: [pull_request]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    timeout-minutes: 10
    if: github.event.pull_request.draft == false
    name: Run lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd # v7.0.0
        with:
          only-new-issues: true
